### PR TITLE
choose-file button styled

### PR DESCRIPTION
**Pull request by irosikoni**
image

### CODE REVIEW

**Comment by MCzech3605** [comment]
I don't think the tooltip is needed, it duplicates the information

**Comment by irosikoni** [comment]
[Screencast from 2024-04-14 23-43-51.webm](https://github.com/Zajmujemy-Dzieci/zajmujemy-dzieci/assets/108950456/394caca7-84ef-42a4-8602-d1be0af956f4)

**Comment by yoinker57** [comment]
jest pięknie

**Review by yoinker57 — APPROVED** [review]
good work

**Pull request merged**
